### ISSUE TITLE
Retrieving annotations from PDF

### ISSUE THREAD

**Issue by AtomicNess123** [malb/emacs.d#1]
Excellent init file! I was wondering if `malb/pdf-annot-export-as-org ` retrieves notes made with `org-noter`. It seems that it doesn't. So this would retrieve all annotations made except with `org-noter`, can you confirm this? Thanks.

**Comment by malb** [comment]
Yep, it only deals with annotations stored in the PDF itself. I guess merging them with some org-noter notes shouldn't be too hard but I don't use it.
